[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist"

[context.develop]
  command = "npm run dev"
  publish = "dist"
